import { createPublicClient, http } from "viem";
import { base } from "viem/chains";
import { LiquidSDK } from "liquid-sdk";
import { getCached, setCache } from "./cache";
import preScannedData from "./tokens-data.json";

export const DEPLOY_BLOCK = BigInt(43327823);
const CHUNK_SIZE = BigInt(10000); // Public Base RPC limits eth_getLogs to 10,000 blocks
const CONCURRENCY = 5;
const TOKEN_CACHE_TTL = 5 * 60 * 1000; // 5 minutes
const RECENT_SCAN_BLOCKS = BigInt(100000); // Scan last 100K blocks for new tokens

export interface ScannedToken {
  address: string;
  name: string;
  symbol: string;
  image: string;
  poolId: string;
  hook: string;
  creator: string;
  blockNumber: number;
}

// Load pre-scanned tokens from the JSON file (generated by scripts/scan-tokens.mjs)
function getPreScannedTokens(): ScannedToken[] {
  return preScannedData.tokens as ScannedToken[];
}

function createSDK() {
  const publicClient = createPublicClient({
    chain: base,
    transport: http(process.env.BASE_RPC_URL || "https://mainnet.base.org"),
  });
  return new LiquidSDK({ publicClient });
}

export function getPublicClient() {
  return createPublicClient({
    chain: base,
    transport: http(process.env.BASE_RPC_URL || "https://mainnet.base.org"),
  });
}

async function scanChunk(
  sdk: ReturnType<typeof createSDK>,
  fromBlock: bigint,
  toBlock: bigint
): Promise<ScannedToken[]> {
  try {
    const tokens = await sdk.getTokens({ fromBlock, toBlock });
    return tokens.map((token) => ({
      address: token.tokenAddress,
      name: token.tokenName,
      symbol: token.tokenSymbol,
      image: token.tokenImage,
      poolId: token.poolId,
      hook: token.poolHook,
      creator: token.msgSender,
      blockNumber: Number(token.blockNumber ?? 0),
    }));
  } catch (error) {
    console.error(`Chunk ${fromBlock}-${toBlock} failed:`, error);
    return [];
  }
}

export async function scanAllTokens(): Promise<ScannedToken[]> {
  // Check cache first
  const cached = getCached<ScannedToken[]>("all_tokens", TOKEN_CACHE_TTL);
  if (cached) return cached;

  // Start with pre-scanned tokens
  const preScanned = getPreScannedTokens();
  const scannedBlock = preScannedData.scannedAtBlock;

  // Scan recent blocks for new tokens
  const publicClient = getPublicClient();
  const currentBlock = await publicClient.getBlockNumber();
  const scanFrom =
    BigInt(scannedBlock) > RECENT_SCAN_BLOCKS
      ? BigInt(scannedBlock) - RECENT_SCAN_BLOCKS
      : BigInt(scannedBlock);

  const sdk = createSDK();
  const recentTokens: ScannedToken[] = [];

  // Build chunks for recent scan
  const chunks: { from: bigint; to: bigint }[] = [];
  let fromBlock = scanFrom;
  while (fromBlock < currentBlock) {
    const toBlock =
      fromBlock + CHUNK_SIZE > currentBlock
        ? currentBlock
        : fromBlock + CHUNK_SIZE;
    chunks.push({ from: fromBlock, to: toBlock });
    fromBlock = toBlock + BigInt(1);
  }

  // Scan in parallel
  for (let i = 0; i < chunks.length; i += CONCURRENCY) {
    const batch = chunks.slice(i, i + CONCURRENCY);
    const results = await Promise.allSettled(
      batch.map((chunk) => scanChunk(sdk, chunk.from, chunk.to))
    );
    for (const result of results) {
      if (result.status === "fulfilled") {
        recentTokens.push(...result.value);
      }
    }
  }

  // Merge: pre-scanned + recent, deduplicate by address (prefer newer block)
  const tokenMap = new Map<string, ScannedToken>();
  for (const token of preScanned) {
    tokenMap.set(token.address.toLowerCase(), token);
  }
  for (const token of recentTokens) {
    const existing = tokenMap.get(token.address.toLowerCase());
    if (!existing || token.blockNumber > existing.blockNumber) {
      tokenMap.set(token.address.toLowerCase(), token);
    }
  }

  const allTokens = Array.from(tokenMap.values());
  allTokens.sort((a, b) => b.blockNumber - a.blockNumber);

  setCache("all_tokens", allTokens, TOKEN_CACHE_TTL);
  return allTokens;
}
